name: Generate and Deploy Slides

on:
  push:
    branches: [ main ]
    paths:
      - 'slides.md'
      - 'figs/*'

jobs:
  generate-slides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important pour les opérations Git ultérieures

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Generate HTML slides
        run: |
          marp slides.md --html --allow-local-files -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: false
          force_orphan: false  # Important pour ne pas essayer de réinitialiser la branche
          disable_nojekyll: true  # Puisque vous avez déjà ajouté .nojekyll